name: 'Post JIRA Comment'
description: 'Post a comment linking to the JIRA ticket for the pull request'
inputs:
  github_token:
    description: The GitHub API token to use for authenticated requests
    default: ${{ github.token }}
    required: false
  jira_user:
    description: 'User for making requests to JIRA'
    required: true
  jira_password:
    description: 'Password for making requests to JIRA'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
