name: 'Build with UBP'
description: 'Creates a build with UBP'

inputs:
  jsonFiles:
    description: 'The files you want to build with space delimited'
    required: true
  override:
    description: 'The override JSON for the job'
    required: true
  platform:
    description: 'The target platform (AndroidGoogle, AndroidAmazon, AndroidSamsung, AndroidFacebook, WebGLFacebook, IOS, MacOS, Win, Win64)'
    required: true
  unityVersion:
    description: 'The version of unity for building'
    required: true
  buildMethod:
    description: 'Set a custom method to build with for UBP'
    default: 'JamCity.UnityCore.UnifiedBuildPipelineSdk.Editor.Commands.BuildPlayerFromFile'
    required: false
  logFile:
    description: 'Allows setting of optional logfile'
    default: '-'
    required: false
  unityLocation: 'Allows setting of custom location where the different version of unity are stored'
    default: '/Applications/Unity/Hub/Editor/'
    required: false


runs:
  using: composite
  steps:
    - name: 'Run UBP'
      env: 
        UNITY_COMMAND: '${{inputs.unityLocation}}${{ inputs.unityVersion }}/Unity.app/Contents/MacOS/Unity -projectPath ${{ github.workspace }} -batchmode -logfile ${{inputs.logFile}}'
        EXECUTE_METHOD: '-executeMethod ${{inputs.buildMethod}} -withParams ${{inputs.jsonFiles}} override.json'
        BUILD_TARGET: '-buildTarget'
      run: |
        echo Writing override file: override.json
        cat <<EOF | tee override.json
        ${{inputs.override}}
        EOF

        echo files to run "${{inputs.jsonFiles}}"

        #Determine launch platform
        case `echo ${{inputs.platform}} | tr '[:upper:]' '[:lower:]'` in
           "macos")
              LAUNCH_PLATFORM=StandaloneOSX
              ;;
           "android*")
              LAUNCH_PLATFORM=Android
              ;;
           "WebGLFacebook")
              LAUNCH_PLATFORM=WebGL
              ;;
           *)
             LAUNCH_PLATFORM=${{inputs.platform}}
             ;;
        esac

        FULL_COMMAND="$UNITY_COMMAND $BUILD_TARGET $LAUNCH_PLATFORM $EXECUTE_METHOD"
        echo $FULL_COMMAND
        $FULL_COMMAND
      shell: bash
