name: 'Build with UBP'
description: 'Creates a build with UBP'

inputs:
  files:
    description: 'The files you want to build with space delimited'
    required: true
  override:
    description: 'Your override json for the job'
    required: true
  platform:
    description: 'The target platform'
    required: true
  unityVersion:
    description: 'The version of unity for building'
    required: true
  buildMethod:
    description: 'Set a custom method to build with for UBP'
    default: 'JamCity.UnityCore.UnifiedBuildPipelineSdk.Editor.Commands.BuildPlayerFromFile'
    required: false
  logFile:
    description: 'Allows setting of optional logfile'
    default: '-'
    required: false

runs:
  using: composite
  steps:
    - name: 'Run UBP'
      env: 
        UNITY_COMMAND: '/Applications/Unity/Hub/Editor/${{ inputs.unityVersion }}/Unity.app/Contents/MacOS/Unity -projectPath ${{ github.workspace }} -batchmode -logfile ${{logFile}}'
        EXECUTE_METHOD: '-executeMethod ${{inputs.buildMethod}} -withParams ${{inputs.files}} override.json'
        BUILD_TARGET: '-buildTarget'
      run: |
        echo Writing override file: override.json
        cat <<EOF | tee override.json
        ${{inputs.override}}
        EOF

        echo files to run "${{inputs.files}}"

        #Determine launch platform
        case `echo ${{inputs.platform}} | tr '[:upper:]' '[:lower:]'` in
           "macos")
              LAUNCH_PLATFORM=StandaloneOSX
              ;;
           "androidgoogle")
              LAUNCH_PLATFORM=Android
              ;;
           *)
             LAUNCH_PLATFORM=${{inputs.platform}}
             ;;
        esac

        FULL_COMMAND="$UNITY_COMMAND $BUILD_TARGET $LAUNCH_PLATFORM $EXECUTE_METHOD"
        echo $FULL_COMMAND
        $FULL_COMMAND
      shell: bash
