name: 'CHANGELOG.md updated'
description: 'Check that CHANGELOG.md has been updated with this pull request'
inputs:
  github_token:
    description: The GitHub API token to use for authenticated requests
    default: ${{ github.token }}
    required: false
  filename:
    description: Filename to check for changes
    default: CHANGELOG.md
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
