name: 'Package Snapshot'

on:
  workflow_call:
    inputs:
      sdk_name:
        type: string
        required: true
      branch:
        type: string
        required: true
      version:
        type: string
        required: true
    secrets:
      artifactory_root:
        required: true
      artifactory_user:
        required: true
      artifactory_password:
        required: true

jobs:
  build-and-release-package:
    name: 'Build and Release Snapshot'
    runs-on: ['self-hosted', 'macOS', 'unity', 'unity-core']
    defaults:
      run:
        shell: bash

    env:
      PACKAGE_NAME: 'JamCity.${{ inputs.sdk_name }}'
      RELEASE_PATH: 'Assets/Plugins/JamCity/JamCity.${{ inputs.sdk_name }}/Editor/Release'

    steps:
      - name: 'Validate Snapshot Version'
        run: |
          echo "${{ inputs.version }}" | grep -E '^\d+(?:\.\d+){2}$' || (echo 'Specified version number is invalid -- expected format: x.y.z' && false)

      - name: 'Validate Snapshot Branch'
        run: |
          { [ "${{ inputs.branch }}" != 'main' ] && [ "${{ inputs.branch }}" != 'master' ]; } || (echo "Snapshots cannot be made from the '${{ inputs.branch }}' branch" && false)

      - name: Cloning ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: 'Create package'
        working-directory: ${{ env.RELEASE_PATH }}
        run: ./gradlew createPackage
        env:
          PACKAGE_VERSION: '${{ inputs.version }}-SNAPSHOT'

      - name: 'Rename zip artifact'
        working-directory: ${{ env.RELEASE_PATH }}/build/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}
        run: mv package.zip ${{ env.PACKAGE_NAME }}.zip

      - name: 'Publish to Artifactory'
        uses: mindjolt/actions/package-manager-publish@v2
        with:
          rootUrl: ${{ secrets.artifactory_root }}
          user: ${{ secrets.artifactory_user }}
          password: ${{ secrets.artifactory_password }}
          packageZip: ${{ env.RELEASE_PATH }}/build/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}.zip
          packageJson: ${{ env.RELEASE_PATH }}/build/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}/package.json
          branchRef: ${{ inputs.branch }}

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v2
        with:
          path: |
            Editor/Release/build/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}.zip
            Editor/Release/build/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}/package.json
