name: 'Quality Checks'

on:
  workflow_call:
    inputs:
      sdk_name:
        type: string
        required: true
      target_ref:
        type: string
        required: true
    secrets:
      confluence_user:
        required: true
      confluence_password:
        required: true

jobs:
  post-jira-comment:
    name: 'Post JIRA Comment'
    runs-on: ['self-hosted', 'k8s-svc-runners-dind']
    steps:
      - name: 'Check for existing comment and post if necessary'
        uses: mindjolt/uc-actions/post-jira-comment@main
        with:
          jira_user: ${{ secrets.confluence_user }}
          jira_password: ${{ secrets.confluence_password }}

  check-for-changelog:
    name: 'CHANGELOG.md updated'
    runs-on: ['self-hosted', 'k8s-svc-runners-dind']
    steps:
      - name: 'Search for CHANGELOG.md update'
        uses: mindjolt/uc-actions/check-for-changelog@main

  check-for-documentation:
    name: 'Documentation updated'
    runs-on: ['self-hosted', 'k8s-svc-runners-dind']
    steps:
      - name: 'Search for Documentation update'
        uses: mindjolt/uc-actions/check-for-documentation@main
        with:
          jira_user: ${{ secrets.confluence_user }}
          jira_password: ${{ secrets.confluence_password }}
