name: 'Test Builds'

on:
  workflow_call:
    inputs:
      sdk_name:
        type: string
        required: true
      target_ref:
        type: string
        required: true
      enable_submodules:
        type: boolean
        default: false
        required: false
    secrets:
      artifactory_root:
        required: true
      mj_github_token:
        required: true

jobs:
  make-builds:
    name: 'Build Player'
    runs-on: ['self-hosted', 'macOS', 'unity', 'unity-core']
    strategy:
      fail-fast: false
      matrix:
        TARGET_PLATFORM: ['Android', 'Amazon', 'OSX', 'iOS', 'WebGL', 'Windows']
        UNITY_VERSION: ['2019.4.28f1']
        include:
          - TARGET_PLATFORM: 'Android'
            UNITY_PLATFORM: 'Android'
            EXTRA_ARGUMENT: ''

          - TARGET_PLATFORM: 'Amazon'
            UNITY_PLATFORM: 'Android'
            EXTRA_ARGUMENT: ' -Amazon'

          - TARGET_PLATFORM: 'OSX'
            UNITY_PLATFORM: 'OSXUniversal'
            EXTRA_ARGUMENT: ''

          - TARGET_PLATFORM: 'iOS'
            UNITY_PLATFORM: 'iOS'
            EXTRA_ARGUMENT: ''

          - TARGET_PLATFORM: 'WebGL'
            UNITY_PLATFORM: 'WebGL'
            EXTRA_ARGUMENT: ''

          - TARGET_PLATFORM: 'Windows'
            UNITY_PLATFORM: 'StandaloneWindows64'
            EXTRA_ARGUMENT: ''
    env:
      TARGET_PACKAGE: 'JamCity.${{ inputs.sdk_name }}'
      UNITY_COMMAND: '/Applications/Unity/Hub/Editor/${{ matrix.UNITY_VERSION }}/Unity.app/Contents/MacOS/Unity -buildTarget ${{ matrix.UNITY_PLATFORM }} -projectPath ${{ github.workspace }}/${{ matrix.UNITY_VERSION }} -batchmode -logfile -'
      EXECUTE_INSTALL_PACKAGE: '-executeMethod JamCity.UnityCoreTests.Editor.PackageCatalogUtility.InstallPackage -withParams'
      BUILD_PLAYER: '-executeMethod Builder.BuildPlayer${{ matrix.EXTRA_ARGUMENT }} -quit'
      PACKAGE_PATH: '${{ github.workspace }}/Target/Assets/Plugins/JamCity/JamCity.${{ inputs.sdk_name }}'
      MANIFEST_PATH: '${{github.workspace }}/${{ matrix.UNITY_VERSION }}/Packages/manifest.json'

    steps:
      - name: 'Checkout UnityCoreTests'
        uses: actions/checkout@v2
        with:
          repository: mindjolt/UnityCoreTests
          token: ${{ secrets.mj_github_token }}

      - name: 'Checkout Package'
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.target_ref }}
          path: ${{ github.workspace }}/Target
          token: ${{ fromJSON(inputs.enable_submodules) && secrets.mj_github_token || github.token }}
          submodules: ${{ fromJSON(inputs.enable_submodules) && 'recursive' || 'false' }}

      - name: 'Set Unity Version'
        run: ln -s ${{ github.workspace }}/Source ${{ github.workspace }}/${{ matrix.UNITY_VERSION }}/Assets

      - name: 'Determine Package Version'
        id: 'package_version'
        run: |
          echo "value=$(jq -r '.version' ${{ env.PACKAGE_PATH }}/package.json)" >> $GITHUB_OUTPUT

      - name: 'Create Package'
        id: 'create_package'
        uses: mindjolt/uc-actions/create-package@main
        with:
          artifactory_root: ${{ secrets.artifactory_root }}
          package_version: ${{ steps.package_version.outputs.value }}
          source_path: ${{ env.PACKAGE_PATH }}

      - name: 'Configure Unity Packages'
        run: |
          if [[ -f "${{ github.workspace }}/Target/Packages/manifest.json" ]]; then
              echo $(jq -s '.[0] * .[1]' "${{ github.workspace }}/Target/Packages/manifest.json" "${{ env.MANIFEST_PATH }}") > "${{ env.MANIFEST_PATH }}"
          fi

      - name: 'Install Required Dependencies'
        run: ${{ env.UNITY_COMMAND }} ${{ env.EXECUTE_INSTALL_PACKAGE }} ${{ steps.create_package.outputs.zip_path }}

      - name: 'Build Player'
        run: ${{ env.UNITY_COMMAND }} ${{ env.BUILD_PLAYER }}
